downloader:
  thunder:
    host: "https://thunder.levicy.love"
    port: 443 
logger:
  debugFileName: "logs/debug.log"
  infoFileName: "logs/info.log"
  warnFileName: "logs/warn.log"
  errorFileName: "logs/error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3