server:
  port: 8088

passport:
  username: "admin"
  password: "123456"

downloader:
  thunder:
    host: "http://192.168.0.111"
    port: 2345 

jwt:
  secret: 4Bde3BGEbYqtqyEUzW4ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ3s
  jwt_ttl: 432000

logger:
  debugFileName: "logs/debug.log"
  infoFileName: "logs/info.log"
  warnFileName: "logs/warn.log"
  errorFileName: "logs/error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3

mysql:
  driver: mysql # 数据库驱动
  # host: net-blog-go-mysql # 域名
  host: 127.0.0.1
  port: 3306 # 端口号
  database: nas-spider # 数据库名称
  # username: work # 用户名
  username: root
  # password: Mysqlxwy9264! # 密码
  password: 123456
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log # 日志文件名称