downloader:
  thunder:
    host: "http://192.168.0.111"
    port: 2345 
logger:
  debugFileName: "logs/debug.log"
  infoFileName: "logs/info.log"
  warnFileName: "logs/warn.log"
  errorFileName: "logs/error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3